# Generated by Django 5.0.6 on 2024-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
